### ISSUE TITLE
How to use target option?

### ISSUE THREAD

**Issue by mrmark** [splitsh/lite#10]
When I try to use the `--target=some-new-branch` option I get this error:

    The target is not a valid Git reference

My understanding was that the target option took a branch name that does not exist and that it would create the branch after the split.  Is this incorrect?  Is target instead supposed to be used to _add_ new commits to an existing split stored in an existing branch?

Cheers and thanks!

**Comment by fabpot** [comment]
From docs: --target creates a reference for the tip of the split (can be any Git reference like HEAD, heads/xxx, tags/xxx, origin/xxx, or any refs/xxx)

So, it should be `heads/some-new-branch` to create a new branch or override an existing one.

**Comment by benito103e** [comment]
@fabpot it doesn't work for me.

see #31
