### ISSUE TITLE
Syntax errors on getting/building

### ISSUE THREAD

**Issue by tbureck** [splitsh/lite#16]
Hi,

I'm getting syntax errors when I try to get or build splitsh. These are the messages:

```
→ go get github.com/splitsh/lite
# github.com/splitsh/lite
src/github.com/splitsh/lite/main.go:87: syntax error: unexpected range, expecting {
src/github.com/splitsh/lite/main.go:93: non-declaration statement outside function body
src/github.com/splitsh/lite/main.go:97: non-declaration statement outside function body
src/github.com/splitsh/lite/main.go:101: non-declaration statement outside function body
src/github.com/splitsh/lite/main.go:105: non-declaration statement outside function body
src/github.com/splitsh/lite/main.go:109: non-declaration statement outside function body
src/github.com/splitsh/lite/main.go:110: syntax error: unexpected }
```

My go version is

```
→ go version
go version go1.3.3 linux/amd64
``

Unfortunately I don't have any clue about Go, so I don't know what to do at all. :(

Best regards

**Comment by philippecarle** [comment]
Range syntax has been implemented in 1.4, so you should consider upgrading your go version (current stable version is 1.6).
Depending on your environment and which package manager you used, you can `brew upgrade go` on Mac OS X, or `sudo apt-get install golang` on Debian / Ubuntu.

**Comment by fabpot** [comment]
Closing as this is a matter of upgrading Go (1.3 is quite old now).

**Comment by tbureck** [comment]
Thanks, I've just installed from the normal Debian Jessie repository. Using the testing repository now. :)
