### ISSUE TITLE
Build on Windows using MSYS2

### ISSUE THREAD

**Issue by torinaki** [splitsh/lite#18]
It possible to compile splitsh on Windows using MinGW. 
Follow these steps to prepare MSYS2 enviroment:
https://github.com/libgit2/git2go/pull/307
After you will be able to follow standart installation processin MSYS2 bash console:
https://github.com/splitsh/lite#installation

**Comment by fabpot** [comment]
Closing this issue as I don't think there is anything to do on our side.
