### ISSUE TITLE
Possible to pick individual files?

### ISSUE THREAD

**Issue by lkraav** [splitsh/lite#19]
https://github.com/Automattic/jetpack/tree/master/modules has a complex structure. To split individual modules, you'd need to pick a set of files and directories from all over the tree.

Target module is significant enough to be worth some hassle. Any advice here?

**Comment by fabpot** [comment]
The way splitsh works is by creating commits out of Git trees. As individual files are not stored in a tree, there is unfortunately nothing I can do to support this use case (unless someone has an idea).

**Comment by lkraav** [comment]
Looks like `git fast-export` and `git fast-import` are the solutions via https://stackoverflow.com/questions/39479154/how-can-i-split-a-single-file-from-a-git-repo-into-a-new-repo
