### ISSUE TITLE
Support for splitting tags

### ISSUE THREAD

**Issue by kdambekalns** [splitsh/lite#21]
While this is already awesome (in terms of speed, minus issue #20), it is rather useless without being able to also split tags… at least for us.

Instead of building tagging ourselves, is there anything else we could do, except hope? Maybe even a timeframe for the non-light version?

Or maybe we'll just email you as suggested in the readme and let you split our stuff :)

**Comment by kdambekalns** [comment]
Hm, thinking about it… I could just use ` --origin=refs/tags/1.2.3` when splitting and push the result as the very same tag to my remote target, no? Everything is just a reference…

**Comment by fabpot** [comment]
Yes, you should never split a tag as it is just a reference to a commit. That being said, the full version contains code that allows to synchronize tags on the main repo with the tags on the splits. All the code is actually in the lite version, but not the plumbing. I will try to add a new command that makes it easier to find which sha to tag in the splits, based on a tag from the main repo.

**Comment by kdambekalns** [comment]
Well, but I tried and just used `refs/tags/…` for a test and it showed up fine, attached to the expected commit. Are there any drawbacks of doing this?

Here is the result repo of the results: https://github.com/kdambekalns/test-flow/releases

**Comment by fabpot** [comment]
Sure, that's probably the easiest thing to do.

**Comment by craigh** [comment]
@fabpot or @kdambekalns - I'm sorry to tag on to an old ticket.

Could you give an example of how I might use `--origin=refs/tags/1.2.3` in order to push tags to remotes of the split repos? I am not a git expert ... and so I need some more simple instructions.

I've seen other approaches online, but wonder if this seems the best, so need more info please.

**Comment by kdambekalns** [comment]
@craigh I needed to look it up, as we still did not switch to using splitsh. But the actual call happens in https://github.com/neos/slicer/pull/8/files#diff-042fb6249166b33daaeff3cc2af8754aR159-R164 and the `$ref` that is passed would just be `refs/tags/x.y.z` as passed by GitHub in our case… Hope that helps.
