### ISSUE TITLE
Combine many repos into a new monorepo

### ISSUE THREAD

**Issue by redthor** [splitsh/lite#23]
Thanks for splitsh-lite.

I have a question. Can I use splitsh-lite to create a new monorepo from many minirepos?

My use case is that we manage our code out of a lot repos which we then bring in via composer. I would like to establish a new monorepo that contains the base application as well as all our internally developed dependencies.

e.g.

```
.git/
app/
dep1/
dep2/
depN/
```

**Comment by aslakhellesoy** [comment]
I'm also interested in this. I've got several repositories with years of commit history. I'd like to keep that history (at least for the master branch) when I bring them all into the same monorepo.

Is this possible?

**Comment by mmunro-ltrr** [comment]
I'm interested in this as well, & rolled some quick and dirty demonstrations to show what might work. There's a project spread over many repositories at the moment, each with their own histories. A simple invocation of the standard command-line git can combine these into a monorepo (see https://bitbucket.org/mmunro-ltrr/uaqs_repository_tools for a shell script that does this). The current version of splitsh-lite doesn't preserve the histories of the combined repositories, but there's a hacked-around fork at https://github.com/ltrr-arizona-edu/lite that will do this. I've just been re-basing the extra code on top of the updates that appear here, but now might be the time to tidy it up & make a proper pull request.

**Comment by aslakhellesoy** [comment]
Thanks for the pointers @mmunro-ltrr - very useful!

**Comment by redthor** [comment]
Yes, thanks @mmunro-ltrr - I'm digesting your code at the moment. Cheers!

**Comment by benoitc** [comment]
what's the status of this command?

**Comment by sergeyz** [comment]
@benoitc please check if it works for you https://github.com/splitsh/lite/pull/26

**Comment by karser** [comment]
Using [tomono](https://github.com/unravelin/tomono) I was able to create mono repo from many ones and keep the history.
Notice: Make sure that your git version at least 2.9 or greater.

Usage:

Prepare a list of repositories to merge in a file, for example repos.txt:
```
git@github.com:mycompany/service-one.git one
git@github.com:mycompany/service-two.git two
git@github.com:mycompany/service-three.git three
```

```
$ cat repos.txt | ~/tomono/tomono.sh
```
This will create a new repository called core, in your current directory.
