### ISSUE TITLE
Where are the binaries?

### ISSUE THREAD

**Issue by alex-pex** [splitsh/lite#28]
> The fastest way to get started is to download a [binary](https://github.com/splitsh/lite/releases) for your platform.

Where is it?
I'd like to use Travis-CI to split my monolytic repository. Do you have an example of how to do it?

**Comment by beeman** [comment]
I would be interested in this too

**Comment by jdpedrie** [comment]
+1

**Comment by fabpot** [comment]
Fixed now. I've uploaded binaries for Linux and MacOs.
