### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by theofidry** [splitsh/lite#3]
>If you want to learn more about monorepo vs manyrepos, watch this 4-minutes lightning talk I gave at dotScale... or the longer version from DrupalCon.

There is no links :(

**Comment by trackleft** [comment]
https://www.youtube.com/watch?v=4w3-f6Xhvu8

**Comment by fabpot** [comment]
I've just added the DrupalCon link and I will add he dotScale one when the video is published.
