### ISSUE TITLE
splitsh (non lite?)

### ISSUE THREAD

**Issue by singularo** [splitsh/lite#34]
In the DrupalCon New Orleans 2016: The Symfony Monolith Repository video, you are using splitsh, but its not the version released here and appears to have a lot more features than this splitsh/lite, just curious if that more advanced splitsh  is going to be released as well, or made available as a service or something.

**Comment by collizo4sky** [comment]
Any comment @fabpot ?

**Comment by fabpot** [comment]
I don't have plans to release the full version. That would require too much work, and I don't expect to have the time needed to do that work anytime soon.
