### ISSUE TITLE
Create online service/github app that would split repositories

### ISSUE THREAD

**Issue by Koc** [splitsh/lite#38]
It would be cool create some online service that can integrates with Github by webhooks (listen push events) and automatically split repositories by provided config (for example `.split.yaml`)

**Comment by Westie** [comment]
I've written something like this (in an experimental capacity using splitsh-lite) for work.

I am considering releasing it publicly on Github (work is good like that, as long as I ask first) but would you be hosting it yourself @Koc, or would you be wanting a third-party hosted solution?

**Comment by Koc** [comment]
https://github.com/symplify/monorepo-split-github-action
