### ISSUE TITLE
Commit hashes different between splitsh-lite and git subtree split, part II

### ISSUE THREAD

**Issue by kdambekalns** [splitsh/lite#39]
This is named like #20, but a different bug, as far as we know.

The commit neos/flow-development-collection@882be01390260ef055d3897ff2165eedc0222cb4 results in neos/flow@4d563e683b436670c45eff44d1f241bda9f971ba right now, using the subtree split. Splitting using splitsh it ends up in kdambekalns/flow@79cae3e5373fb02c1e2214c94b23732a4865742e. The latter looks exactly like the commit from the development collection…

Looking further, there is no difference between the results, but the hashes differ. To maximise confusion, GitHub actually shows a difference, locally Git says it's the same (https://github.com/neos/flow/compare/3.0...kdambekalns:3.0-splitsh?expand=1 vs. `git diff 3.0..3.0-splitsh` after cloning kdambekalns/flow)

The split was done using `splitsh-lite --prefix=TYPO3.Flow --origin=origin/3.0 --target=refs/heads/3.0-splitsh`

**Comment by kdambekalns** [comment]
To top it off, we created a PR from the "difference" at https://github.com/kdambekalns/flow/pull/1 that showed differences in 20 files. We wanted to have fun and merged that, resulting in no changes (see https://github.com/kdambekalns/flow/commit/f5d167dadedb63ea7f957e8bf5eeb0069440943a) - which we expected, since the changes the PR wanted to do, actually existed in the base branch.

After the merge, the fork is now 23 commits ahead of the original, but again (as expected), no differences: https://github.com/neos/flow/compare/3.0...kdambekalns:3.0?expand=1

So, this might even be a bug in git and/or git-subsplit, and splitsh actually gets it right.

**Comment by kdambekalns** [comment]
No bug in GitHub, it’s caused by a “two dot” vs “three dot” diff. But the difference between the results is real.

**Comment by kdambekalns** [comment]
Anyone feels like being able to help with finding out the cause for this?

**Comment by dxops** [comment]
I think you have the same case like we discussed some time ago in https://github.com/splitsh/lite/pull/26#issuecomment-298010883

**Comment by cebe** [comment]
sounds similar to https://github.com/yiisoft/yii2/issues/15785#issuecomment-368860963
