### ISSUE TITLE
Sync tags between master and slave repos

### ISSUE THREAD

**Issue by sneppy** [splitsh/lite#47]
I would like to push the tag along with the commit when pushing to a slave repo.

Right now what I do is run `splitsh-lite --prefix=lib`, take the SHA1 of the commit and push the commit to the master branch of the slave repo:

```
git push <slave_remote> <SHA1_commit>:master
```

can I attach a tag to the generated commit and push it along?

**Comment by mmunro-ltrr** [comment]
Yes, it's possible to push tags from the monorepo to the various manyrepos. We're doing it with a shell script that gets invoked in the particular CI environment we're using:
https://bitbucket.org/ua_drupal/uaqs_repository_tools/src/7.x-1.x/tagsplits.sh
This also tries to update CHANGELOG.txt files, & I found it confusing that the tag actually gets repeatedly replaced in the monorepo to end up in the correct position, after all the changes. In this example the name for splitsh-lite is in the  `UAQSRTOOLS_SPLITTER` environment variable (`lite` by default).
