### ISSUE TITLE
Object not found - no match for id (xxxx)

### ISSUE THREAD

**Issue by elmpp** [splitsh/lite#51]
Please can someone give me a hint as to why i would be seeing this? 

 * It is happening for multiple packages of my monorepo. 
 * The SHA1s given are present in their relevant manyrepo. 
 * This process has been functioning very well (thanks!) for a number of months before today

It is quite possible that i have deleted a tag from the manyrepo between the last "sync" but without an understanding of this tool/subtrees I'm a little lost (no experience of Go)

**Comment by elmpp** [comment]
appears was a broken git working copy as recloning from origin fixed. Thanks

**Comment by stefandanaita** [comment]
Here's a fix if it happens on Github actions: https://github.com/antalaron/action-splitsh/issues/1
