### ISSUE TITLE
Error when build on Windows 10 

### ISSUE THREAD

**Issue by ireneaguilar-seat** [splitsh/lite#58]
Hello,

I am trying to install splitsh-lite in windows 10. I read https://github.com/splitsh/lite/issues/18 and followed the manual instructions until the last step when an error is thrown:

In cmd:
>go get github.com/splitsh/lite
# github.com/libgit2/git2go
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgit2
collect2.exe: error: ld returned 1 exit status

In MINGW64:
$ go build -o splitsh-lite github.com/splitsh/lite
# github.com/libgit2/git2go
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgit2
collect2.exe: error: ld returned 1 exit status

Could you help me or give me some guidelines in order to build splitsh-lite?

Thank you!

**Comment by fabpot** [comment]
Unfortunately, I'm not using Windows, so I have no idea. Perhaps ask on StackOverflow.
