### ISSUE TITLE
Segfault on big sur / Apple silicon

### ISSUE THREAD

**Issue by acrobat** [splitsh/lite#61]
I don't know if it's related to big sur or the new apple M1 chip but I get a segmentation fault when executing the binary.

```
→ ./splitsh-lite
[1]    79703 segmentation fault  ./splitsh-lite

→ lldb ./splitsh-lite
(lldb) target create "./splitsh-lite"
Current executable set to './splitsh-lite' (x86_64).
(lldb) run
Process 79368 launched: './splitsh-lite' (x86_64)
Process 79368 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xf1)
    frame #0: 0x0000000004051805 splitsh-lite`main + 933
splitsh-lite`main:
->  0x4051805 <+933>: movl   $0xf1, 0xf1
    0x4051810 <+944>: retq
    0x4051811 <+945>: int3
    0x4051812 <+946>: int3
Target 0: (splitsh-lite) stopped.
(lldb)
```

**Comment by onanying** [comment]
me too

**Comment by vinhha96** [comment]
Me too. :(

**Comment by vinhha96** [comment]
Have you found a solution to this problem @acrobat ?

**Comment by stefandanaita** [comment]
Same here..

**Comment by fabpot** [comment]
Have you compiled the binary from source? If not, you should. If yes, someone needs to investigate the issue and submit a PR to fix it (I'm not on a Mac anymore).

**Comment by jenskueper** [comment]
I can recommend using https://github.com/newren/git-filter-repo as a replacement for splitsh under arm64 architectures.

https://github.com/newren/git-filter-repo
