### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by kdambekalns** [splitsh/lite#68]
Seeing the last release is still from 2017, Go module support is still not merged, PRs are not being looked at… I wonder if this is still supported/maintained?

We switched to it for the Neos project because it was just so fast… and now we'll switch to `git-filter-repo` as that works fine on ARM64, is just way easier to use (read: no need to compile anything yourself against ageing libraries) and about as fast. _And_ supported…

- If this project is no longer maintained: **Thanks for the past, it served us well!**
- If it's still alive: Good luck for the future!

Either way, it would be nice to clarify the state, so people can get their expectations right.

**Comment by fabpot** [comment]
I've indeed limited time to dedicate to this project.
I'm in the process of releasing a new version.
Thank you for your PR about go mod.

**Comment by fabpot** [comment]
I've just released v2.0.0.
