### ISSUE TITLE
Many CVE Issues

### ISSUE THREAD

**Issue by smikuszeit** [splitsh/lite#70]
Dear all,

since this great binary is used in laravel-framework it would be very nice when you update to a newer go version.

https://www.cvedetails.com/vulnerability-list/vendor_id-14185/product_id-29205/version_id-1035689/Golang-GO-1.13.8.html

Very thanks for this great project !

Regards,
Stefan

**Comment by fabpot** [comment]
We're working on this as we're moving to use go.mod.
