### ISSUE TITLE
Oh god, you do not love PHP anymore? 

### ISSUE THREAD

**Issue by netroby** [splitsh/lite#8]
-_-||

You came to written golang now .
You do not love PHP anymore. 

Otherwise, this project should written with PHP .

**Comment by GrahamCampbell** [comment]
> You do not love PHP anymore.

I'm not sure@fabpot ever "loved" PHP. Haha. Pleased this is written in Go. It's such a nice language. ;)

**Comment by fabpot** [comment]
Who said that you should only ever use one language? Good luck writing this in PHP :) Or at least, the full version that is not yet open-sourced. I try to use the best tool for the job. Anyway, closing now.
